"""adds track url and track_image_url field to track model

Revision ID: a838d93d41cf
Revises: 39d538ffdebf
Create Date: 2021-07-01 16:53:46.055563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a838d93d41cf'
down_revision = '39d538ffdebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('url', sa.String(length=100), nullable=True))
    op.add_column('tracks', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'image_url')
    op.drop_column('tracks', 'url')
    # ### end Alembic commands ###
